package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.demo.requestBodyModel.NewInventoryRequestBody;

import java.util.Map;

// Type | Region | Brand | Value | Status | Code | Order#
// combination sort key: china:Apple:100:unused:code
@DynamoDBDocument
@DynamoDBTable(tableName = "inventory")
public class Inventory {
    @DynamoDBHashKey(attributeName = "type")
    @DynamoDBAutoGeneratedKey
    private String type;

    @DynamoDBRangeKey(attributeName = "info")
    private Map<String, Object> info;

    @DynamoDBAttribute(attributeName = "region")
    private String region;

    @DynamoDBAttribute(attributeName = "brand")
    private String brand;

    @DynamoDBAttribute(attributeName = "value")
    private Integer value;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

    @DynamoDBAttribute(attributeName = "code")
    private String code;

    @DynamoDBAttribute(attributeName = "order_number")
    private String order_number;

    public Inventory(){};

    public Inventory(NewInventoryRequestBody requestBody) {
        this.type = requestBody.getType().toString();
        this.region = requestBody.getRegion().toString();
        this.brand = requestBody.getRegion().toString();
        this.value = requestBody.getValue();
        this.status = requestBody.getStatus().toString();
        this.code = requestBody.getCode();
        this.order_number = requestBody.getOrder_number();
    }
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Map<String, Object> getInfo() {
        return info;
    }

    public void setInfo(Map<String, Object> info) {
        this.info = info;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getOrder_number() {
        return order_number;
    }

    public void setOrder_number(String order_number) {
        this.order_number = order_number;
    }
}
